### ISSUE TITLE
Convert Time into "Unix time Stamp"

### ISSUE THREAD

**Issue by namrashah** [namrashah/Predicting-Stock-Movements#1]

**Comment by namrashah** [comment]
Prepared a dictionary that maps the existing values of time and its values. If the value of time is repeated then we can assign the value directly from the dictionary. There are 2498 different values.

**Comment by namrashah** [comment]
To make it more efficient we can remove the existing key in dictionary every time a new value of time is encountered. That way the dictionary will have only 1 value to look at which will make it even more efficient.

**Comment by namrashah** [comment]
If we can somehow get the frequency of each value of count, then there's no need of a dictionary and will make the code even more efficient.

**Comment by kanika-rawat** [comment]
Converting into Unix timestamp was taking long time so we just converted time into 2 columns of date and hours
